// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc-ZLEEym_1U1Q_9_ozCLnHGmZonEyO40',
    appId: '1:379144739641:web:77febd098d8d642024e6e8',
    messagingSenderId: '379144739641',
    projectId: 'chat-misis-app',
    authDomain: 'chat-misis-app.firebaseapp.com',
    storageBucket: 'chat-misis-app.appspot.com',
    measurementId: 'G-E6336C24EY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZHFe8fv1fWP2pBdZHRcGbHusBK_mfCBg',
    appId: '1:379144739641:android:85b5f6ed4f9029e824e6e8',
    messagingSenderId: '379144739641',
    projectId: 'chat-misis-app',
    storageBucket: 'chat-misis-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGNi80eACdRXNh4NENOklOICTXFawVWA0',
    appId: '1:379144739641:ios:c612b71b921df08124e6e8',
    messagingSenderId: '379144739641',
    projectId: 'chat-misis-app',
    storageBucket: 'chat-misis-app.appspot.com',
    iosClientId: '379144739641-p4duonv96tu186ikobbht6sqam8f9ugt.apps.googleusercontent.com',
    iosBundleId: 'com.example.vkExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGNi80eACdRXNh4NENOklOICTXFawVWA0',
    appId: '1:379144739641:ios:c612b71b921df08124e6e8',
    messagingSenderId: '379144739641',
    projectId: 'chat-misis-app',
    storageBucket: 'chat-misis-app.appspot.com',
    iosClientId: '379144739641-p4duonv96tu186ikobbht6sqam8f9ugt.apps.googleusercontent.com',
    iosBundleId: 'com.example.vkExample',
  );
}
