// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdwA_eNQOm5ILcWgRrp9rjEoBGfMxjbPU',
    appId: '1:722782611654:web:59dc617b97feec40908fc7',
    messagingSenderId: '722782611654',
    projectId: 'todo-list-d28fe',
    authDomain: 'todo-list-d28fe.firebaseapp.com',
    storageBucket: 'todo-list-d28fe.appspot.com',
    measurementId: 'G-YR8D3DWNWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPYRlLtT3RNZcVSebTOuQYOJ3cYFTarO0',
    appId: '1:722782611654:android:cf3483c568130680908fc7',
    messagingSenderId: '722782611654',
    projectId: 'todo-list-d28fe',
    storageBucket: 'todo-list-d28fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPNpC7b9fqypxKva3seYZ8z2SLIJl_fMI',
    appId: '1:722782611654:ios:e3170e44dd43c067908fc7',
    messagingSenderId: '722782611654',
    projectId: 'todo-list-d28fe',
    storageBucket: 'todo-list-d28fe.appspot.com',
    iosClientId: '722782611654-rufs3nejgatshqhqc4gfgrvomlcan4ic.apps.googleusercontent.com',
    iosBundleId: 'com.example.vkExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPNpC7b9fqypxKva3seYZ8z2SLIJl_fMI',
    appId: '1:722782611654:ios:e3170e44dd43c067908fc7',
    messagingSenderId: '722782611654',
    projectId: 'todo-list-d28fe',
    storageBucket: 'todo-list-d28fe.appspot.com',
    iosClientId: '722782611654-rufs3nejgatshqhqc4gfgrvomlcan4ic.apps.googleusercontent.com',
    iosBundleId: 'com.example.vkExample',
  );
}
